job/urls.py
from django.urls import path
from . import views
from . import api
urlpatterns = [

    #fbv
    path('',views.jobs,name='home'),
    path('job-details/<slug:slug>',views.job_details,name='job-details'),
    path('post-job/',views.post_job,name='post_job'),

    #cbv
    path('cbv/',views.JobList.as_view(),name='JobList'),
    path('cbv/job-details/<slug:slug>',views.JobDetail.as_view(),name='JobDetail'),
    path('cbv/post-job/',views.PostJob.as_view(),name='PostJob'),



    #API
    path('api/',api.JobList.as_view(),name='JobList'),
    path('api/<slug:slug>',api.JobDetail.as_view(),name='JobDetail'),
]

jobboard/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('',include('job.urls')),
    path('contact/',include('contact.urls')),
    path('blog/',include('blog.urls')),
    *static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
    path('api-auth/', include('rest_framework.urls'))


]

job/models.py
from django.db import models
from django.contrib.auth.models import User
from slugify import slugify
def image_upload(instance,filename):
    (image_names,extension) = (filename.split('.'))
    return f'jobs/{instance.id}.{extension}'

class job(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    job_type_choices = (
        ('Full time', 'Full time'),
        ('Part time', 'Part time')
    )
    job_type = models.CharField(max_length=15, choices=job_type_choices)
    description = models.TextField(max_length=500)
    publish_at = models.DateTimeField(auto_now=True)
    salary = models.IntegerField(default=1200)
    vacancy = models.IntegerField(default= 1)
    experince = models.IntegerField(default= 0)
    categorie = models.ForeignKey("categorie", on_delete=models.CASCADE)
    image = models.ImageField( upload_to= image_upload, height_field=None, width_field=None, max_length=None)
    slug = models.SlugField(null=True,blank=True,unique=True)
    def __str__(self) -> str:
        return self.title

    def save(self,*args, **kwargs):
        self.slug = slugify(self.title,to_lower=True)
        super(job,self).save(*args, **kwargs)
    


class categorie(models.Model):
    categorie = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.categorie

class apply_job(models.Model):
    job = models.ForeignKey('job', on_delete=models.CASCADE)
    name = models.CharField( max_length=50)
    email = models.EmailField(max_length=254)
    website = models.URLField(max_length=200)
    cv = models.FileField(upload_to='cv', max_length=100)
    coverletter = models.TextField(max_length=200)

    def __str__(self) -> str:
        return self.name

job/views.py
from django.views.generic import ListView , DetailView , FormView
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from accounts.models import profile
from .models import *
from django.shortcuts import redirect ,render
from django.core.paginator import Paginator
from .form import *
from django.contrib.auth.decorators import login_required




#----------------------using fbv------------------------------------------------------------------------------------------------------------
def jobs(request):
    all_jobs = job.objects.all()
    job_filter = filter(request.GET)
    if job_filter.is_valid():
        if job_filter.cleaned_data['title'] != '':
            all_jobs =all_jobs.filter(title__icontains= job_filter.cleaned_data['title'])
        if job_filter.cleaned_data['experince'] != None :
            all_jobs =all_jobs.filter(experince = job_filter.cleaned_data['experince'])
        if job_filter.cleaned_data['salary'] != None :
            all_jobs =all_jobs.filter(salary  = job_filter.cleaned_data['salary'])
        if job_filter.cleaned_data['categorie'] != None :
            all_jobs =all_jobs.filter(categorie=job_filter.cleaned_data['categorie'])
        if job_filter.cleaned_data['job_type'] != '':
            all_jobs =all_jobs.filter(job_type= job_filter.cleaned_data['job_type'])
    paginator = Paginator(all_jobs,4)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = { 'jobs'          : page_obj,
                'all_jobs'      : all_jobs,
                'filter_form'   : job_filter,
                }
    return render(request,'job/jobs.html',context=context)

#------------------------------ using CBV ----------------------------------------
class JobList(ListView):
    queryset = job.objects.all()
    paginate_by = 2
    template_name ='job/jobs_cbv.html'
    
    def get(self,*args, **kwargs):
        self.form = filter(self.request.GET)
        if self.form.is_valid():
            if self.form.cleaned_data['title'] != '':
                self.queryset =self.queryset.filter(title__icontains= self.form.cleaned_data['title'])
            if self.form.cleaned_data['experince'] != None :
                self.queryset =self.queryset.filter(experince = self.form.cleaned_data['experince'])
            if self.form.cleaned_data['salary'] != None :
                self.queryset =self.queryset.filter(salary  = self.form.cleaned_data['salary'])
            if self.form.cleaned_data['categorie'] != None :
                self.queryset =self.queryset.filter(categorie=self.form.cleaned_data['categorie'])
            if self.form.cleaned_data['job_type'] != '':
                self.queryset =self.queryset.filter(job_type= self.form.cleaned_data['job_type'])
        return super().get(self,*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.form 
        return context
    


#----------------------using fbv------------------------------------------------------------------------------------------------------------
def job_details(request,slug):
    
    job_detail = job.objects.get(slug=slug)
    if request.method == 'POST':
        apply_form = apply(request.POST,request.FILES)
        if apply_form.is_valid():
            myform = apply_form.save(commit=False)
            myform.job =job_detail
            myform.save()
            return redirect('/')
    else:
        apply_form = apply()

    context = {'job': job_detail,'apply_form':apply_form}
    return render(request,'job/job_details.html',context=context)


class JobDetail(FormMixin,DetailView):
    model = job
    template_name ='job/job_details_cbv.html'
    form_class = apply

    def post(self,*args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        return super().post(self,*args, **kwargs)

    def form_valid(self, form):
        myform = form.save(commit=False)
        myform.job = job.objects.get(slug=self.kwargs['slug'])
        myform.save()
        return super().form_valid(form)

    def get_success_url(self) :
        return reverse('JobDetail',kwargs={'slug':self.kwargs['slug']})







#------------------------------ using CBV ----------------------------------------
@login_required
def post_job(request):
    if request.method == 'POST':
        job_form = job_post_form(request.POST,request.FILES)
        if job_form.is_valid():
            myform = job_form.save(commit=False)
            myform.user = request.user
            myform.save()
            job_slug = job.objects.get(title=myform.title)
            return redirect(f'/job-details/{job_slug.slug}')
    else:
        job_form = job_post_form()
    context = {'post_job':job_form}
    return render(request,'job/job_post.html',context)

#------------------------------ using CBV ----------------------------------------
class PostJob(LoginRequiredMixin,FormView):
    form_class = job_post_form
    template_name = "job/job_post_cbv.html"

    def get_success_url(self) -> str:
        return reverse('JobDetail',kwargs={'slug':self.slug})

    def form_valid(self, form):
        myform = form.save(commit=False)
        myform.user = self.request.user
        myform.save()
        self.slug = myform.slug
        return super().form_valid(form)

templates/job/applyied.html
{% extends 'base/base.html' %}

<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
{% block body %}
    
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>You have been applied</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}
</body>

</html>

templates/job/job_details.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}

<!doctype html>


<body>
    {% block body %}
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img src="img/svg_icon/1.svg" alt="">
                                </div>
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{job.title}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i>{{job.job_type}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Job description</h4>
                            <p>{{job.description}}</p>
                        </div>
                    </div>
                    <div class="apply_job_form white-bg">
                        <h4>Apply for the job</h4>
                        <form enctype="multipart/form-data" method="POST">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="input_field">
                                        {{apply_form.name}}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="input_field">
                                        {{apply_form.email}}
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="input_field">
                                        {{apply_form.website}}
                                    </div>
                                </div>
                                <div class="col-md-12">
                                          {% bootstrap_field apply_form.cv %}
                                </div>
                                <div class="col-md-12">
                                    <div class="input_field">
                                        {{apply_form.coverletter}}
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="submit_btn">
                                        <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Published on: <span>{{job.publish_at|date:"d M Y"}}</span></li>
                                <li>Vacancy: <span>{{job.vacancy}} Position</span></li>
                                <li>Salary: <span>{{job.salary}} LE</span></li>
                                <li>Job Nature: <span> {{job.job_type}}</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock body %}
</body>

</html>

templates/job/job_details_cbv.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}

<!doctype html>


<body>
    {% block body %}
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img src="img/svg_icon/1.svg" alt="">
                                </div>
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{job.title}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i>{{job.job_type}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Job description</h4>
                            <p>{{job.description}}</p>
                        </div>
                    </div>
                    <div class="apply_job_form white-bg">
                        <h4>Apply for the job</h4>
                        <form enctype="multipart/form-data" method="POST">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="input_field">
                                        {{form.name}}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="input_field">
                                        {{form.email}}
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="input_field">
                                        {{form.website}}
                                    </div>
                                </div>
                                <div class="col-md-12">
                                          {% bootstrap_field form.cv %}
                                </div>
                                <div class="col-md-12">
                                    <div class="input_field">
                                        {{form.coverletter}}
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="submit_btn">
                                        <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Published on: <span>{{job.publish_at|date:"d M Y"}}</span></li>
                                <li>Vacancy: <span>{{job.vacancy}} Position</span></li>
                                <li>Salary: <span>{{job.salary}} LE</span></li>
                                <li>Job Nature: <span> {{job.job_type}}</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock body %}
</body>

</html>

templates/job/job_post.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% block body %}
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>Post Job</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<!-- job_listing_area_start  -->
<div class="job_listing_area plus_padding">
    <div class="container">
            <div class="col-lg-9">
                <form enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    {% bootstrap_field  post_job.title layout='horizontal'  %}
                    {% bootstrap_field  post_job.job_type layout='horizontal' %}
                    {% bootstrap_field  post_job.salary layout='horizontal' %}
                    {% bootstrap_field  post_job.vacancy layout='horizontal' %}
                    {% bootstrap_field  post_job.experince layout='horizontal' %}
                    {% bootstrap_field  post_job.image layout='horizontal' %}
                    {% bootstrap_field  post_job.categorie layout='horizontal'  %}
                    {% bootstrap_field  post_job.description layout='horizontal'  %}
                    <div class="col-md-12">
                        <div class="submit_btn">
                            <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                        </div>
                    </div>
                </form>
            </div>
    </div>
</div>
{% endblock body %}

templates/job/job_post_cbv.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% block body %}
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>Post Job</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<!-- job_listing_area_start  -->
<div class="job_listing_area plus_padding">
    <div class="container">
            <div class="col-lg-9">
                <form enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    {% bootstrap_field  form.title layout='horizontal'  %}
                    {% bootstrap_field  form.job_type layout='horizontal' %}
                    {% bootstrap_field  form.salary layout='horizontal' %}
                    {% bootstrap_field  form.vacancy layout='horizontal' %}
                    {% bootstrap_field  form.experince layout='horizontal' %}
                    {% bootstrap_field  form.image layout='horizontal' %}
                    {% bootstrap_field  form.categorie layout='horizontal'  %}
                    {% bootstrap_field  form.description layout='horizontal'  %}
                    <div class="col-md-12">
                        <div class="submit_btn">
                            <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                        </div>
                    </div>
                </form>
            </div>
    </div>
</div>
{% endblock body %}

templates/job/jobs_cbv.html
{% extends 'base/base.html' %}
{% load static %}

{% block body %}
<!doctype html>
<html class="no-js" lang="zxx">

    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    
    <!-- header-end -->

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>+{{job_list|length}} Jobs Available</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form method="GET">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="single_field">
                                            <label readonly style="border:0; color:#7A838B; font-size: 16px; font-weight:400;">{{form.title.name|title}}</label>
                                            {{form.title}}
                                            {% comment %} <input type="text" name="title" placeholder="Search keyword"> {% endcomment %}
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="single_field">
                                            <label readonly style="border:0; color:#7A838B; font-size: 16px; font-weight:400;">{{form.categorie.name|title}}</label>
                                            {{form.categorie}}
                                            {% comment %} <select class="wide" name="categoriez">
                                                <option data-display="Category">Category</option>
                                                {% for cat in category %}
                                                <option value="{{cat}}">{{cat|title}}</option>
                                                {% endfor %}
                                            </select> {% endcomment %}
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="single_field">
                                            <label readonly style="border:0; color:#7A838B; font-size: 16px; font-weight:400;">{{form.experince.name|title}}</label>
                                            {{form.experince}}
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="single_field">
                                            <label readonly style="border:0; color:#7A838B; font-size: 16px; font-weight:400;">Job Type</label>
                                            {{form.job_type}}
                                            {% comment %} <select class="wide" name="job_type">
                                                <option data-display="Job type" >Job type</option>
                                                <option value="Full time">Full time</option>
                                                <option value="Part time">Part time</option>
                                            </select> {% endcomment %}
                                        </div>
                                    </div>
                                </div>
                                <div class="single_field">
                                    <label readonly style="border:0; color:#7A838B; font-size: 18px; font-weight:400;">{{form.salary.name|title}}</label>
                                    {{form.salary}}
                                </div>
                                <div class="col-md-12">
                                    <div class="submit_btn">
                                        <button class="boxed-btn3 w-100" type="submit">Reset</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Job Listing</h4>
                                </div>
                                <div class="col-md-6">  
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                            <div class="col-lg-12 col-md-12">
                                {% for job in job_list %}
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb">
                                            <img src=''  alt="">
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'job-details' job.slug %}"><h4>{{job}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i>{{job.job_type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                                            <a href="{% url 'job-details' job.slug %}" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>Date line: {{job.publish_at|date:"d M Y"}}</p>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% include 'base/paginator.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock body %}
</html>